name: McGeneral
main: com.main.General
version: 0.0.11
author: govagent26
database: false
description: McGeneral is a combination of many bukkit plugins.
commands:
  alias:
    aliases: [a, ac, an, ar, ah]
    description: changes a players display name.
    usage: >
           alias/a- shows the player's display name
           ac- shows the player's display name color
           ac (color)- changes player's name color to (color)
           an- shows the player's display name without color
           an (name)- changes player's name to (name)
           ar- reloads the alias data from the yaml file
           ah- alias help, shows all alias commands to sender
           Only in-game players may use the alias commands
  emote:
    aliases: [me, e]
    description: sends an emote to players in a radius.
    usage: >
           emote/me/e- sends an emote to players
           Only in-game players may use the emote command
  prefix:
    aliases: [p, pc, pn, pr, ph]
    description: changes a players prefix.
    usage: >
           prefix/p- shows the player's prefix
           pc- shows the player's prefix color
           pc (color)- changes player's prefix color to (color)
           pn- shows the player's prefix without color
           pn (prefix)- changes player's prefix to (prefix)
           pr- reloads the prefix data from the yaml file
           ph- prefix help, shows all prefix commands to sender
           Only in-game players may use the prefix commands

  time:
    aliases: [t, ta, ti, tm, tf, tr, th]
    description: can retrieve time and display to sender.
    usage: >
           time/t- displays the time to sender
           ta- displays whether time announcements are on or off
           ta on/off- changes announcing status to on or off
           ti- displays the time interval
           ti (number)- changes interval to (number)
           tm- displays the time message
           tm (message)- changes message to (message)
           tf- displays the time format
           tf 12/24- changes format to 12 or 24 hours
           tr- reloads time data from the yaml file
           th- time help, shows all time commands to sender
  who:
    aliases: list
    description: shows who is online to sender.
    usage: who/list- shows a list of online players to sender