name: McGeneral
main: com.main.General
version: 0.0.10
author: govagent26
database: true
description: McGeneral is a combination of many bukkit plugins.
commands:
  alias:
    aliases: [a, ]
    description: changes a players display name.
    usage: 
  emote:
    aliases: [me, e]
    description: sends an emote to players in a radius.
    usage: >
           emote/me/e- sends an emote to players
           Only in-game players may use the emote command
  time:
    aliases: [t, ta, ti, tm, tf, th]
    description: can retrieve time and display to sender.
    usage: >
           time/t- displays the time to sender
           ta- displays whether time announcements are on or off
           ta on/off- changes announcing status to on or off
           ti- displays the time interval
           ti (number)- changes interval to (number)
           tm- displays the time message
           tm (message)- changes message to (message)
           tf- displays the time format
           tf 12/24- changes format to 12 or 24 hours
           th- time help, shows all time commands to sender
  who:
    aliases: list
    description: shows who is online to sender.
    usage: who/list- shows a list of online players to sender